version: '3.9'

services:
    db:
      image: mysql:8.0
      container_name: bots-db
      command: --default-authentication-plugin=mysql_native_password
      restart: unless-stopped
      ports:
        - ${DB_PORT}:3306
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_SQL_DATABASE}
      volumes:
        - ${DB_PATH_HOST}:${DB_PATH_CONTAINER}
      networks:
        - backend

    redis:
      image: redis:7.0
      container_name: bots-redis
      build:
        args:
          password: ${REDIS_PASSWORD}
        context: ./images/redis
        dockerfile: Dockerfile
      restart: unless-stopped
      ports:
        - ${REDIS_PORT}:6379
      networks:
        - backend

    adminer:
      image: adminer:4.8.1
      container_name: bots-adminer
      restart: unless-stopped
      ports:
        - ${ADMINER_PORT}:8080
      networks:
        - backend
      depends_on:
        - db

    app:
      image: app:1.0
      container_name: bots-app
      build: ./images/php-fpm
      restart: unless-stopped
      working_dir: ${APP_PATH_CONTAINER}
      volumes:
        - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        - ${PHP_INI_HOST}:${PHP_INI_CONTAINER}
        - ${PROJECT_LOGS_HOST}:${PROJECT_LOGS_CONTAINER}
      networks:
        - backend
      depends_on:
        - db
        - redis

    nginx:
      image: nginx:1.21
      container_name: bots-nginx
      restart: unless-stopped
      working_dir: ${APP_PATH_CONTAINER}
      ports:
        - ${NGINX_PORT}:80
      volumes:
        - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        - ${NGINX_SETTINGS_HOST}:${NGINX_SETTINGS_CONTAINER}
        - ${NGINX_PASS_HOST}:${NGINX_PASS_CONTAINER}
        - ${NGINX_LOGS_HOST}:${NGINX_LOGS_CONTAINER}
      links:
          - app
      networks:
        - backend

networks:
  backend:
    name: bots-backend
    driver: bridge
