version: '3.7'
services:
    php:
      build: ./images/php-web
      environment:
        APACHE_RUN_USER: www-data
      volumes:
        - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        - ${PROJECT_LOGS_HOST}:${PROJECT_LOGS_CONTAINER}
      ports:
        - 8080:80
      working_dir: ${APP_PATH_CONTAINER}
    db:
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: bots
      volumes:
        - ${DB_PATH_HOST}:/var/lib/mysql
    adminer:
      image: adminer
      restart: always
      ports:
        - 6080:8080
    composer:
      image: composer:2.3
      volumes:
        - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
      working_dir: ${APP_PATH_CONTAINER}
      command: composer install
